name: 'Merge to Development'
permissions: write-all

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: branch_name
        required: true

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch the whole history to prevent unrelated history errors
          fetch-depth: '0'

      - name: Merge Fast Forward
        uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
        with:
          # Branch to merge
          branchtomerge: ${{ github.event.inputs.branch_name }}
          # Branch that will be updated
          branch: develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}